site_name: Skogstua fellesverksted
site_url: https://www.tromsoskapere.no/docs # <--- Bytt ut med din URL
repo_url: https://github.com/Tromsoskapere/mkdocs-skogstua/ # <--- Bytt ut med din repo-URL
repo_name: Se på GitHub

theme:
  name: material
  language: nb
  logo: logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Bytt til mørkt tema
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Bytt til lyst tema
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  # - awesome-pages  # deprecated and renamed to awesome-nav
  - awesome-nav
  # - section-index
  - pagetree
  # - macros
  - search

