site_name: Skogstua fellesverksted
site_url: https://docs.tromsoskapere.no/ 
repo_url: https://github.com/Tromsoskapere/mkdocs-skogstua/ 
repo_name: mkdocs-skogstua

theme:
  name: material
  language: nb
  logo: logo.svg
  favicon: logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Bytt til mørkt tema
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Bytt til lyst tema
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight

plugins:
  - awesome-nav
# - section-index
  - pagetree
  - search

extra_css:
  - assets/extra.css
