site_name: Skogstua fellesverksted
site_url: https://tromsoskapere.github.io/mkdocs-skogstua # <--- Bytt ut med din URL
repo_url: https://github.com/Tromsoskapere/mkdocs-skogstua/ # <--- Bytt ut med din repo-URL
repo_name: Se på GitHub

theme:
  name: material
  # logo: assets/logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Bytt til mørkt tema
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Bytt til lyst tema
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - awesome-pages
  - search
  - section-index
  - macros:
      module_name: main

define_env:
  !python |
    def define_env(env):
        """
        This is the hook for the macros plugin, defined inline.
        """
        @env.macro
        def hello_world():
            """
            A simple test macro to confirm the connection.
            """
            return "### Success! The inline macro is working in GitHub Actions."

